image:
  app:
    url: 981130112916.dkr.ecr.us-east-1.amazonaws.com/biomes/client
    tag: latest
    pullPolicy: IfNotPresent
    pullSecret: ""

port: 3000
targetPort: 3000

replicas: 2

resources:
  limits:
    cpu: 0.2
    memory: 128M
  requests:
    cpu: 0.1
    memory: 64M
